apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-broken
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-broken
  template:
    metadata:
      labels:
        app: nginx-broken
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80